### ISSUE TITLE
SQL Error - Pugin not using password upon login

### ISSUE THREAD

**Issue by Champion0912** [ModdedMinecraft/MMCTickets#18]
I am getting the same error with this plugin as with a few others, it seems like the SQL module is not up to date for newer SQL versions and therefore it is not able to input the password correctly upon logging into the database.

Error:

[11:19:03] [Server thread/INFO] [mmctickets]: Loading datastore: MySQL
[11:19:03] [Server thread/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-3 - Starting...
[11:19:04] [Server thread/ERROR] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-3 - Exception during pool initialization.
java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user 'ticketuser'@'localhost' (using password: NO)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:154) ~[ExceptionMapper.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118) ~[ExceptionMapper.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.throwException(ExceptionMapper.java:92) ~[ExceptionMapper.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.mariadb.jdbc.Driver.connect(Driver.java:111) ~[Driver.class:1.12.2-2705-7.1.0-BETA-3481]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112) ~[DriverDataSource.class:1.12.2-2705-7.1.0-BETA-3481]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[PoolBase.class:1.12.2-2705-7.1.0-BETA-3481]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[PoolBase.class:1.12.2-2705-7.1.0-BETA-3481]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443) [HikariPool.class:1.12.2-2705-7.1.0-BETA-3481]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514) [HikariPool.class:1.12.2-2705-7.1.0-BETA-3481]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111) [HikariPool.class:1.12.2-2705-7.1.0-BETA-3481]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97) [HikariDataSource.class:1.12.2-2705-7.1.0-BETA-3481]
	at net.moddedminecraft.mmctickets.database.MYSQLDataStore.getConnection(MYSQLDataStore.java:262) [MYSQLDataStore.class:?]
	at net.moddedminecraft.mmctickets.database.MYSQLDataStore.load(MYSQLDataStore.java:37) [MYSQLDataStore.class:?]
	at net.moddedminecraft.mmctickets.database.DataStoreManager.load(DataStoreManager.java:30) [DataStoreManager.class:?]
	at net.moddedminecraft.mmctickets.Main.onServerAboutStart(Main.java:88) [Main.class:?]
	at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_Main_onServerAboutStart37.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:231) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:271) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3481]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:864) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:291) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:268) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.sql.SQLException: Could not connect: Access denied for user 'ticketuser'@'localhost' (using password: NO)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:772) ~[AbstractConnectProtocol.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:701) ~[AbstractConnectProtocol.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:406) ~[AbstractConnectProtocol.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1029) ~[AbstractConnectProtocol.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:483) ~[Utils.class:1.12.2-2705-7.1.0-BETA-3481]
	at org.mariadb.jdbc.Driver.connect(Driver.java:106) ~[Driver.class:1.12.2-2705-7.1.0-BETA-3481]
	... 49 more

**Comment by leelawd** [comment]
Try putting " " around the password in the config

**Comment by Champion0912** [comment]
Already tried. No change in error :/

**Comment by Champion0912** [comment]
Here's a copy of the SQL part of my config:

mysql {
        # The database to store in
        database=ticketdata
        # Host of the MySQL Server
        host=localhost
        # Password for that user
        password=PasswordHiddenForCopyPaste
        # Port of the MySQL server. Default: 3306
        port="3306"
        # Prefix for the plugin tables
        table-prefix="mmctickets_"
        # The user for the database
        user=ticketuser

**Comment by leelawd** [comment]
Could you check your log to see if there is any other errors thrown before this one?

My only suspect atm is certain special characters being substituted for other things

**Comment by Champion0912** [comment]
No errors from MMCtickets before this one.
I have also tried to change SQL's password validity to accept password without special characters and changed the password, as many other plugins states errors with passwords including special characters.
No luck..

**Comment by leelawd** [comment]
Can you try using this? All that was changed was updating HikariCP and importing it into the package.
Since i saw that Sponge currently uses a different version, Im unsure if it will actually fix it or not though.

https://github.com/SpongePowered/SpongeCommon/blob/ef9b72f8ef04ad163445994776637d707a94de8c/build.gradle#L70

ultimately though, if this is the issue, Sponge should be informed and see about updating it on their end

**Comment by Champion0912** [comment]
No change in error I'm afraid.
Here's the error message in its hole:
https://pastebin.com/KY27tQ5b


Could the mistake be on my end?
Am I suppose to use an older version on MYSQL for Sponge?
Because I am getting this and similar error with nearly all Sponge plugins except Luckperms.
Currently using 8.0.15.

**Comment by leelawd** [comment]
After a little hunting around i found this
https://github.com/SpongePowered/SpongeCommon/issues/2008

**Comment by Champion0912** [comment]
Should get maker of EconomyLite in here too, I'm getting exactly same bug from his plugin.

**Comment by Champion0912** [comment]
I can't seem to find any way to downgrade from 8 to 5.7, so far only aricles and forums saying it's not possible.

Maybe try to recreate the problem and take it from there?
