### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Foxgreat** [ModdedMinecraft/MMCTickets#9]
I've got error from MMC Ticket on my servers. Can you check it? 
MC 1.12.2
Forge 2555
Sponge 2802
MMCTicket 1.4.0 7.0

```
[03:44:19] [Server thread/ERROR] [Sponge]: Could not pass FMLServerStartedEvent to Plugin{id=mmctickets, name=MMCTickets, version=1.4.0-API7, description=A real time ticket system, source=/srv/ztest/./mods/plugins/MMCTickets-1.4.0-API-7.jar}
java.lang.NumberFormatException: For input string: "140-API7"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_151]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_151]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_151]
	at net.moddedminecraft.mmctickets.util.UpdateChecker.startUpdateCheck(UpdateChecker.java:69) ~[UpdateChecker.class:?]
	at net.moddedminecraft.mmctickets.Main.onServerStart(Main.java:106) ~[Main.class:?]
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_Main_onServerStart38.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.0.0-BETA-2802]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:328) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2802]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:361) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2802]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:232) [SpongeMod.class:1.12.2-2555-7.0.0-BETA-2802]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:561) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:782) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:300) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by leelawd** [comment]
fixed in https://ore.spongepowered.org/leelawd93/MMCTickets/versions/1.4.1
